# Generated by Django 3.2.4 on 2021-06-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarespec',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='softwarespec/'),
        ),
    ]
