# Generated by Django 3.2.4 on 2021-06-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_softwarespec_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='othermatters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='softwarespec',
            name='image',
        ),
    ]
