# Generated by Django 3.2.4 on 2021-06-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_20210627_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarespec',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='input/'),
        ),
    ]
