# Generated by Django 3.2.4 on 2021-07-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0006_auto_20210629_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermatters',
            name='chspecnum',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
