# Generated by Django 3.2.4 on 2021-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_othermatters_chspecnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarespec',
            name='boonryu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
